// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByn6P3UCrAdIKCOfxRS5pY_DjjLfvlRzQ',
    appId: '1:724364547352:web:25786a1aa3a721e08b7a6d',
    messagingSenderId: '724364547352',
    projectId: 'binnydb-c2557',
    authDomain: 'binnydb-c2557.firebaseapp.com',
    storageBucket: 'binnydb-c2557.appspot.com',
    measurementId: 'G-5B3EKKCWT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJDXUBJ6dSc2bK-VEL_qM-oEjN8ZjJbM',
    appId: '1:724364547352:android:90e07c8e87ad79ee8b7a6d',
    messagingSenderId: '724364547352',
    projectId: 'binnydb-c2557',
    storageBucket: 'binnydb-c2557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA472xbjCD2INiZZsEkga78mppGgMBweiI',
    appId: '1:724364547352:ios:58122b1b63a70f548b7a6d',
    messagingSenderId: '724364547352',
    projectId: 'binnydb-c2557',
    storageBucket: 'binnydb-c2557.appspot.com',
    iosBundleId: 'com.example.loginregister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA472xbjCD2INiZZsEkga78mppGgMBweiI',
    appId: '1:724364547352:ios:58122b1b63a70f548b7a6d',
    messagingSenderId: '724364547352',
    projectId: 'binnydb-c2557',
    storageBucket: 'binnydb-c2557.appspot.com',
    iosBundleId: 'com.example.loginregister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByn6P3UCrAdIKCOfxRS5pY_DjjLfvlRzQ',
    appId: '1:724364547352:web:79809df2da62d6658b7a6d',
    messagingSenderId: '724364547352',
    projectId: 'binnydb-c2557',
    authDomain: 'binnydb-c2557.firebaseapp.com',
    storageBucket: 'binnydb-c2557.appspot.com',
    measurementId: 'G-3RPVBPWTCZ',
  );
}
